import { StyleSheet } from "react-native";
import { Colors } from "../../../common/utils/Enums";

export const styles = StyleSheet.create({
  container: {
    height: "100%",
    backgroundColor: Colors.Light,
  },
  scrollContainer: {
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  logo: {
    width: 200,
    height: 200,
    marginTop: 30,
    marginBottom: 30,
  },
  formContainer: {
    width: "100%",
    height: 350,
    backgroundColor: Colors.Light,
    borderRadius: 0,
    justifyContent: "space-evenly",
    marginBottom: 10,
    padding: 10,
    paddingBottom: 40,
    elevation: 5,
  },
  buttonsContainer: {
    width: "92%",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  label: {
    fontSize: 20,
    fontWeight: "bold",
    textShadowColor: Colors.Grey,
    textShadowOffset: { width: 0, height: 0.5 },
    textShadowRadius: 10,
    color: "white",
    fontFamily: "FiraSans-Regular",
  },
  errorLabel: {
    fontFamily: "FiraSans-Regular",
    color: Colors.Dark,
    fontSize: 10,
    fontWeight: "normal",
    marginLeft: 10,
  },
  input: {
    borderBottomWidth: 1,
    borderColor: Colors.MediumGrey,
    width: "100%",
    height: 60,
    backgroundColor: Colors.LightGrey,
    fontFamily: "FiraSans-Regular",
    fontSize: 18,
    color: "black",
    paddingLeft: 10,
    marginBottom: 5,
  },
  button: {
    width: 110,
    height: 55,
    backgroundColor: Colors.DarkBlue,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    elevation: 10,
  },
  buttonText: {
    fontSize: 20,
    fontWeight: "normal",
    color: Colors.Light,
    fontFamily: "FiraSans-Regular",
  },
  link: {
    fontSize: 12,
    fontWeight: "bold",
    color: Colors.Grey,
    fontFamily: "FiraSans-Regular",
  },
});
