import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    height: "100%",
    backgroundColor: "#F2561D",
  },
  scrollContainer: {
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  logo: {
    width: 250,
    height: 230,
    marginTop: 30,
    marginBottom: 30,
  },
  formContainer: {
    width: "80%",
    height: 350,
    backgroundColor: "#1f1f1f",
    borderRadius: 0,
    justifyContent: "space-evenly",
    alignItems: "center",
    elevation: 10,
    marginBottom: 20,
  },
  label: {
    fontSize: 20,
    fontWeight: "bold",
    textShadowColor: "#868686",
    textShadowOffset: { width: 0, height: 0.5 },
    textShadowRadius: 10,
    color: "white",
    fontFamily: "FiraSans-Regular",
  },
  errorLabel: {
    fontFamily: "FiraSans-Regular",
    color: "#f75858",
    fontSize: 12,
    fontWeight: "bold",
  },
  input: {
    borderBottomWidth: 1,
    borderColor: "black",
    width: "90%",
    height: 50,
    backgroundColor: "#fff",
    fontFamily: "FiraSans-Regular",
    elevation: 5,
    fontSize: 16,
    color: "black",
  },
  button: {
    width: 80,
    height: 32,
    backgroundColor: "#F2561D",
    borderRadius: 0,
    justifyContent: "center",
    alignItems: "center",
    elevation: 10,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: "bold",
    textShadowColor: "#7a7a7a",
    textShadowOffset: { width: 0, height: 0.5 },
    textShadowRadius: 10,
    color: "#ffffff",
    fontFamily: "FiraSans-Regular",
  },
  link: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#8b8a8a",
    fontFamily: "FiraSans-Regular",
  },
});
